version: '3.6'

services:
  proxy.api:
    container_name: proxy_api
    build:
      context: .
      dockerfile: Prxlk.Gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - 5049:80
    networks:
      - main-network
    depends_on:
      - proxy.db
  proxy.db:
    container_name: proxy_db
    image: "mongo"
    volumes:
      - ./.mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - main-network
  
networks:
  main-network:
    driver: bridge